dashboard/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.signin, name='signin'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('products', views.products, name='products'),
    path('setting', views.setting, name='setting'),
    path('orders', views.orders, name='orders'),
    path('categories', views.categories, name='categories'),
    path('stocks', views.stocks, name='stocks'),
    path('order_status/<int:order_id>/', views.order_status, name='order_status'),
    path('notification', views.notification, name='notification'),
    path('aboutus/', views.inbox, name='inbox'),
    path('basic_details/', views.product_data_collector, name='basic_details'),
    path('inventory/', views.inventory_data_collector, name='inv_details'),
    path('media/', views.media_collection, name='media'),
    path('invoice/', views.invoice, name='invoice'),
    path('add_product/', views.add, name='add'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("inventory.urls",namespace='inventory')),
    path("login/", include("dashboard.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

inventory/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'inventory'
urlpatterns = [
                  path('', views.home, name='home'),
                  path('remove_cart', views.remove_from_cart, name='remove_from_cart'),
                  path('checkout', views.checkout, name='checkout'),
                  path('buy_now/', views.buy_now, name='buy_now'),
                  path('order/', views.order_info, name='order_info'),
                  path('contact/', views.contact, name='contact'),
                  path('aboutus/', views.about, name='about'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theme/templates/theme/base.html
{% load static %}
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Meta Tags -->
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <!-- Stylesheets -->
  <link rel="stylesheet" href="{% static 'inventory/styles.css' %}">
  {% tailwind_css %}

  <title>Nepali Clothing</title>
</head>
<body>

  <!-- Navigation Bar -->
  <header>
    <nav class="navbar bg-black-900">
        <!-- Mobile Menu Button -->
        <div class="bars hidden">
            <button aria-label="Menu">
                <svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512">
                    <path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/>
                </svg>
            </button>
        </div>

        <!-- Brand Logo -->
        <div class="flex-1 nav-brand">
            <a class="btn btn-ghost font-thin" href="{% url 'inventory:home' %}">Nepali Clothing</a>
        </div>

        <!-- Navigation Links -->
        <div class="nav-list">
            <ul class="flex nav-item">
                <li class="nav-link"><a href="{% url 'inventory:home' %}">Home</a></li>
                <li class="nav-link"><a href="#tshirt">T-Shirt</a></li>
                <li class="nav-link"><a href="{% url 'inventory:about' %}">About us</a></li>
                <li class="nav-link"><a href="{% url 'inventory:contact' %}">Contact us</a></li>
            </ul>
        </div>

        <!-- Shopping Cart Button -->
        <div class="flex-none" id="open-drawer" onclick="openDrawer()">
            <button class="btn btn-ghost btn-square" aria-label="Shopping Cart">
                <div class="indicator">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
                    </svg>
                </div>
            </button>
        </div>
    </nav>
  </header>
  <main>
    {% block contact %}{% endblock %}
    {% block Hero %}{% endblock %}
    {% block content %}{% endblock %}
    {% block about %}{% endblock %}
    {% block checkout %}{% endblock %}
  </main>
  <!-- Shopping Cart Drawer -->
  <div class="drawer-content">
    <aside class="overlay-drawer" id="myDrawer">
        <div class="drawer-cards">
            <div class="drawer-card-section">
                <h4 class="text">Your Cart</h4>
            </div>
            <button class="cart-closer" onclick="openDrawer()" aria-label="Close Cart">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" width="20" viewBox="0 0 384 512">
                    <path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z"/>
                </svg>
            </button>
        </div>

        <!-- Cart Items -->
        {% if cart_items %}
            <div class="cart-items">
                {% for item in cart_items %}
                    <div class="view-cart" id="cart-item-{{ item.product.id }}">
                        <ul class="cart-list-item">
                            <li>
                                {% for media in item.media_info %}
                                    <img src="{{ media.url }}" alt="{{ media.alt_text }}" class="cart-img">
                                {% endfor %}
                            </li>
                            <li class="cart-item-info">
                                <div>Quantity: {{ item.quantity }}</div>
                                <div>Total: Rs.{{ item.item_total }}</div>
                                <div>{{ item.product_name }}</div>
                                <form method="post" action="{% url 'inventory:remove_from_cart' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="remove_item_id" value="{{ item.product.id }}">
                                    <button type="submit" class="remove-item-btn">Remove</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                {% endfor %}
                <div class="cart-total">
                    <strong>Total Price: Rs.{{ total_price }}</strong>
                </div>
                <div class="cart-footer">
                    <a href="{% url 'inventory:checkout' %}" class="checkout-btn">Checkout</a>
                </div>
            {% else %}
                <p>Your cart is empty.</p>
            </div>
        {% endif %}
    </aside>
  </div>
  
  <footer class="footer p-10 bg-neutral text-neutral-content">
    <aside>
        <svg width="50" height="50" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current">
            <path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path>
        </svg>
        <p>Nepali Clothing Ltd.<br/>Providing reliable Clothing</p>
    </aside>
    <nav>
        <h3 class="footer-title">Social</h3>
        <div class="grid grid-flow-col gap-4">
            <a href="#" aria-label="Twitter">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
                    <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
                </svg>
            </a>
            <a href="#" aria-label="YouTube">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
                    <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
                </svg>
            </a>
            <a href="#" aria-label="Facebook">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
                    <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
                </svg>
            </a>
        </div>
    </nav>
  </footer>
</body>
<script src="{% static 'inventory/js/main.js' %}"></script>
</html>