dashboard/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.signin, name='signin'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('products', views.products, name='products'),
    path('setting', views.setting, name='setting'),
    path('orders', views.orders, name='orders'),
    path('categories', views.categories, name='categories'),
    path('stocks', views.stocks, name='stocks'),
    path('order_status/<int:order_id>/', views.order_status, name='order_status'),
    path('notification', views.notification, name='notification'),
    path('aboutus/', views.inbox, name='inbox'),
    path('basic_details/', views.product_data_collector, name='basic_details'),
    path('inventory/', views.inventory_data_collector, name='inv_details'),
    path('media/', views.media_collection, name='media'),
    path('invoice/', views.invoice, name='invoice'),
    path('add_product/', views.add, name='add'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("inventory.urls",namespace='inventory')),
    path("login/", include("dashboard.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

inventory/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'inventory'
urlpatterns = [
                  path('', views.home, name='home'),
                  path('remove_cart', views.remove_from_cart, name='remove_from_cart'),
                  path('checkout', views.checkout, name='checkout'),
                  path('buy_now/', views.buy_now, name='buy_now'),
                  path('order/', views.order_info, name='order_info'),
                  path('contact/', views.contact, name='contact'),
                  path('aboutus/', views.about, name='about'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField


class Category(MPTTModel):
    """
    Inventory Category table implemented with MPTT
    """

    name = models.CharField(
        max_length=100,
        null=False,
        unique=False,
        blank=False,
        verbose_name=_("category name"),
        help_text=_("format: required, max-100"),
    )
    slug = models.SlugField(
        max_length=150,
        null=False,
        unique=False,
        blank=False,
        verbose_name=_("category safe URL"),
        help_text=_(
            "format: required, letters, numbers, underscore, or hyphens"
        ),
    )
    is_active = models.BooleanField(
        default=True,
    )

    parent = TreeForeignKey(
        "self",
        on_delete=models.PROTECT,
        related_name="children",
        null=True,
        blank=True,
        unique=False,
        verbose_name=_("parent of category"),
        help_text=_("format: not required"),
    )

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("product category")
        verbose_name_plural = _("product categories")

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Product details table
    """

    web_id = models.CharField(
        max_length=50,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("product website ID"),
        help_text=_("format: required, unique"),
    )
    slug = models.SlugField(
        max_length=255,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("product safe URL"),
        help_text=_(
            "format: required, letters, numbers, underscores or hyphens"
        ),
    )
    name = models.CharField(
        max_length=255,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("product name"),
        help_text=_("format: required, max-255"),
    )
    description = models.TextField(
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("product description"),
        help_text=_("format: required"),
    )

    category = TreeManyToManyField(Category)
    is_active = models.BooleanField(
        unique=False,
        null=False,
        blank=False,
        default=True,
        verbose_name=_("product visibility"),
        help_text=_("format: true=product visible"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name=_("date product created"),
        help_text=_("format: Y-m-d H:M:S"),
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("date product last updated"),
        help_text=_("format: Y-m-d H:M:S"),
    )

    def __str__(self):
        return self.name


class ProductType(models.Model):
    """
    Product type table
    """

    name = models.CharField(
        max_length=255,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("type of product"),
        help_text=_("format: required, unique, max-255"),
    )

    def __str__(self):
        return self.name


class Brand(models.Model):
    """
    Product brand table
    """

    name = models.CharField(
        max_length=255,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("brand name"),
        help_text=_("format: required, unique, max-255"),
    )
    def __str__(self):
        return self.name

class ProductAttribute(models.Model):
    """
    Product attribute table
    """

    name = models.CharField(
        max_length=255,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("product attribute name"),
        help_text=_("format: required, unique, max-255"),
    )
    description = models.TextField(
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("product attribute description"),
        help_text=_("format: required"),
    )

    def __str__(self):
        return self.name


class ProductAttributeValue(models.Model):
    """
    Product attribute value table
    """

    product_attribute = models.ForeignKey(
        ProductAttribute,
        related_name="product_attribute",
        on_delete=models.PROTECT,
    )
    attribute_value = models.CharField(
        max_length=255,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("attribute value"),
        help_text=_("format: required, max-255"),
    )

    def __str__(self):
        return f"{self.product_attribute.name} : {self.attribute_value}"


class ProductInventory(models.Model):
    """
    Product inventory table
    """

    objects = None
    sku = models.CharField(
        max_length=20,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("stock keeping unit"),
        help_text=_("format: required, unique, max-20"),
    )
    upc = models.CharField(
        max_length=12,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("universal product code"),
        help_text=_("format: required, unique, max-12"),
    )
    product_type = models.ForeignKey(
        ProductType, related_name="product_type", on_delete=models.PROTECT
    )
    product = models.ForeignKey(
        Product, related_name="product", on_delete=models.PROTECT
    )
    brand = models.ForeignKey(
        Brand, related_name="brand", on_delete=models.PROTECT
    )
    attribute_value = models.ManyToManyField(
        ProductAttributeValue,
        related_name="product_inventories",  # Rename related_name to avoid conflicts
        through="ProductAttributeValues",  # Use the intermediate model
    )
    is_active = models.BooleanField(
        default=True,

        verbose_name=_("product visibility"),
        help_text=_("format: true=product visible"),
    )
    retail_price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("recommended retail price"),
        help_text=_("format: maximum price 999.99"),
        error_messages={
            "name": {
                "max_length": _("the price must be between 0 and 999.99."),
            },
        },
    )
    store_price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("regular store price"),
        help_text=_("format: maximum price 999.99"),
        error_messages={
            "name": {
                "max_length": _("the price must be between 0 and 999.99."),
            },
        },
    )
    sale_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("sale price"),
        help_text=_("format: maximum price 999.99"),
        error_messages={
            "name": {
                "max_length": _("the price must be between 0 and 999.99."),
            },
        },
    )
    weight = models.FloatField(
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("product weight"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name=_("date sub-product created"),
        help_text=_("format: Y-m-d H:M:S"),
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("date sub-product updated"),
        help_text=_("format: Y-m-d H:M:S"),
    )

    def __str__(self):
        return self.product.name


class Media(models.Model):
    """
    The product image table.
    """

    product_inventory = models.ForeignKey(
        ProductInventory,
        on_delete=models.PROTECT,
        related_name="media_product_inventory",
    )
    image = models.ImageField(
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("product image"),
        upload_to="images/",
        default="images/default.png",
        help_text=_("format: required, default-default.png"),
    )
    alt_text = models.CharField(
        max_length=255,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("alternative text"),
        help_text=_("format: required, max-255"),
    )
    is_feature = models.BooleanField(
        default=False,
        verbose_name=_("product default image"),
        help_text=_("format: default=false, true=default image"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name=_("product visibility"),
        help_text=_("format: Y-m-d H:M:S"),
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("date sub-product created"),
        help_text=_("format: Y-m-d H:M:S"),
    )

    class Meta:
        verbose_name = _("product image")
        verbose_name_plural = _("product images")


class Stock(models.Model):
    objects = None
    product_inventory = models.OneToOneField(
        ProductInventory,
        related_name="product_inventory",
        on_delete=models.PROTECT,
    )
    last_checked = models.DateTimeField(
        unique=False,
        null=True,
        blank=True,
        verbose_name=_("inventory stock check date"),
        help_text=_("format: Y-m-d H:M:S, null-true, blank-true"),
    )
    units = models.IntegerField(
        default=0,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("units/qty of stock"),
        help_text=_("format: required, default-0"),
    )
    units_sold = models.IntegerField(
        default=0,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("units sold to date"),

inventory/views.py
from django.shortcuts import render, redirect
from inventory.models import *
from dashboard.models import *
from django.http import JsonResponse
from django.core.paginator import Paginator
from .models import ProductInventory
from .services.cart_service import CartService
from .services.order_service import CheckoutService
from .services.contact_service import ContactService

def home(request):
    """
    Home page
    :param request:
    :return:
    This sends the item details to the template of home page
    """
    
    shop = ProductInventory.objects.prefetch_related("media_product_inventory").all().order_by('id')  # Add ordering
    
    cart = CartService.add_product_to_carts(request)


    print(cart)
    paginator = Paginator(shop, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'cart_items':cart['cart_items'],
        'total_price':cart['total_price'],
    }

    return render(request, "inventory/product.html", context)

def remove_from_cart(request):
    CartService.remove_from_cart(request)
    return redirect('inventory:home')

def checkout(request):
    cart = CartService.add_product_to_carts(request)

    form_data, cust_id = CheckoutService.save_customer_data(request)
    # If request if post, save user data invoice and change progress

    context = {
        'step': request.GET.get('step', 'fill_info'),
        'form_data': form_data,
        'cust_id': cust_id,
        'cart_items':cart['cart_items'],
        'total_price':cart['total_price'],
    }
    return render(request, "inventory/checkout.html", context)




def buy_now(request):
    if request.method == "POST":
        product_id = request.POST.get('product_id')
        quantity = int(request.POST.get('quantity', 1))

        cart = {product_id: quantity}
        request.session['cart'] = cart
        return redirect('inventory:checkout')
    return redirect('inventory:home')


def contact(request):
    cart = CartService.add_product_to_carts(request)

    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        ContactService.create(name=name, email=email, subject=subject, message=message)
    context = {
        'cart_items':cart['cart_items'],
        'total_price':cart['total_price'],

    }

    return render(request, "inventory/contact.html",context)


def about(request):
    cart = CartService.add_product_to_carts(request)

    context = {
        'cart_items':cart['cart_items'],
        'total_price':cart['total_price'],

    }
    
    return render(request, "inventory/about.html",context)


def order_info(request):
    if request.method == "POST":
        cart: dict = request.session.get('cart', {})
        quantity = cart['1']
        print(cart, quantity)
        customer_id = request.POST.get('cust_id')

        for key, value in cart.items():
            product = ProductInventory.objects.prefetch_related("product").get(pk=key)
            
            CheckoutService.save_order_data(cust_id=customer_id, cart_items=cart, total_price=product.retail_price, product=stock, status=Order.status)    
            
            return redirect('dashboard:checkout')

    return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

inventory/templates/inventory/cart.html
{% extends 'inventory/base.html' %}

{% block content %}
<section class="section" id="tshirt">
    <h3 class="section-title">T-Shirt</h3>

    {% if page_obj %}
    {% for item in page_obj %}
    <div class="item-list">
        <div class="product-list-item">
            <div class="product-list-item-img-wrap">
                {% for media in item.media_product_inventory.all %}
                <img src="{{ media.image }}" alt="{{ media.alt_text }}" class="product-list-images">
                {% endfor %}
            </div>
            <div id="add-to-cart-form" class="item-list-content-warp">
                <h2 class="item-list-title">{{ item.product.name }}</h2>
                <div class="product-list-price">Rs.{{ item.retail_price }}</div>
                <p class="paragraph">{{ item.product.description }}</p>
                <form class="item-add-to-cart" method="POST" action="{% url 'home' %}">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ item.product.pk }}">
                    <input type="number" name="quantity" class="item-count" min="1" value="1">
                    <input type="submit" data-loading-text="Adding to cart..." class="item-submit btn-design" value="Add to Cart">
                    <button type="submit" formaction="{% url 'buy_now' %}" class="item-submit btn-design button-filled">Buy Now</button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="flex justify-center mt-8 mb-8">
        <div class="join">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="join-item btn btn-outline">« Previous</a>
            {% else %}
            <button class="join-item btn btn-disabled ">« Previous</button>
            {% endif %}

            <span class="join-item btn">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="join-item btn btn-outline">Next »</a>
            {% else %}
            <button class="join-item btn btn-disabled">Next »</button>
            {% endif %}
        </div>
    </div>
    {% else %}
    <p>No products available.</p>
    {% endif %}
</section>
{% endblock %}


{% block Hero%}
<div class="swiper-container ml-14 mr-14">
  <div class="swiper-wrapper">
    <div class="swiper-slide flex items-center justify-center">
      <div class="flex-1 mr-8 ml-8">
        <h3 class="font-bold text-lg">Plain White T-shirt</h3>
        <p>This is a description of the first t-shirt in the swiper.</p>
      </div>
      <img src="t-shirt" alt="tshirt" class="shadow-lg rounded-md flex-1" />
    </div>
    <div class="swiper-slide flex items-center justify-center">
      <div class="flex-1 mr-8 ml-8">
        <h3 class="font-bold text-lg">Plain Black T-shirt</h3>
        <p>Best Quality tshirt.</p>
      </div>
      <img src="t-shirt" alt="tshirt" class="shadow-lg rounded-md flex-1" />
    </div>
    <div class="swiper-slide flex items-center justify-center">
      <div class="flex-1 mr-8 ml-8">
        <h3 class="font-bold text-lg">Tshirt 3</h3>
        <p>This is a description of the third t-shirt in the swiper.</p>
      </div>
      <img src="t-shirt" alt="tshirt" class="shadow-lg rounded-md flex-1" />
    </div>
  </div>
</div>
{% endblock %}

inventory/templates/inventory/checkout.html
{% extends 'theme/base.html' %}
{% block checkout %}
<div class=" p-40 flex items-center justify-center">
    <h1 class="text-4xl header-style">Checkout Process</h1>
</div>

<div class="checkout-body">
    <div class="checkout-wrapper">
        <div class="order-steps-wrapper">
            <div class="order-step-item">
                <div class="order-step-title">
                    <div class="checkout-section-title">1.Summary</div>
                </div>
                <div class="order-step-content">
                    <div class="order-items-wrapper">
                        <fieldset class="order-items-content">
                            {% if cart_items %}
                                {% for item in cart_items %}
                                    <div class="order-product">
                                        <div class="order-product-media">
                                            {% for media in item.media_info %}
                                            <img src="{{ media.url }}" alt="{{ media.alt_text }}" class="cart-img">
                                            {% endfor %}
                                        </div>
                                        <div class="order-product-details">
                                            <h2>{{ item.product_name }}</h2>
                                            <p>Quantity: {{ item.quantity }}</p>
                                        </div>
                                        <div class="order-product-price">
                                            <p>Rs.{{ item.retail_price }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <p>No items in cart</p>
                            {% endif %}
                        </fieldset>                            
                    </div>
                </div>
            </div>
            <div class="order-step-item">
                <div class="order-step-content">
                    <form class="customer-info" method="POST" action="?step=buy">
                        {% csrf_token %}
                        <fieldset class="items">
                            <label class="text-field-label">EMAIL *
                                <input class="text-field mt-2" type="email" name="email" required
                                       {% if step == 'buy' %}disabled value="{{ form_data.email }}"{% endif %}>
                            </label>
                            <label class="text-field-label">FULL NAME *
                                <input class="text-field mt-2" type="text" name="name" required
                                       {% if step == 'buy' %}disabled value="{{ form_data.name }}"{% endif %}>
                            </label>
                            <label class="text-field-label">PHONE NUMBER *
                                <input class="text-field mt-2" type="tel" name="phone" required
                                       {% if step == 'buy' %}disabled value="{{ form_data.phone }}"{% endif %}>
                            </label>
                            <label class="text-field-label">STREET ADDRESS *
                                <input class="text-field mt-2" type="text" name="address" required
                                       {% if step == 'buy' %}disabled value="{{ form_data.street }}"{% endif %}>
                            </label>
                            <div class=".check-out-row">
                                <div class="">
                                    <label class="text-field-label">CITY *</label>
                                    <label for="citySelect"></label><select class="text-field" name="city" id="citySelect" required
                                                                            {% if step == 'buy' %}disabled{% endif %}>
                                    <option value="">city</option>
                                    <option value="Bagmati" {% if form_data.city == 'Bagmati' %}selected{% endif %}>Kathmandu</option>
                                    <option value="Banapa" {% if form_data.city == 'Banapa' %}selected{% endif %}>Banapa</option>
                                    <option value="Dhulikal" {% if form_data.city == 'Dhulikal' %}selected{% endif %}>Dhulikal</option>
                                    <option value="Kathmandu" {% if form_data.city == 'Kathmandu' %}selected{% endif %}>Kathmandu</option>
                                    </select>
                                </div>
                                <div class="">
                                    <label class="text-field-label">STATE/PROVINCE *</label>
                                    <label for="stateSelect"></label><select class="text-field" name="state" id="stateSelect" required
                                                                             {% if step == 'buy' %}disabled{% endif %}>
                                    <option value="">Select State/Province</option>
                                    <option value="Bagmati" {% if form_data.state == 'Bagmati' %}selected{% endif %}>Bagmati</option>
                                    </select>
                                </div>
                                <div class="">
                                    <label class="text-field-label">ZIP/POSTAL CODE *</label>
                                    <label>
                                        <input class="text-field mt-2" type="text" name="zip" required
                                               {% if step == 'buy' %}disabled value="{{ form_data.zip_code }}"{% endif %}>
                                    </label>
                                </div>
                            </div>
                            <label class="text-field-label">COUNTRY * {{ cust_id }}</label>
                            <label>
                                <input class="text-field mt-2" type="text" name="country" required
                                       {% if step == 'buy' %}disabled value="{{ form_data.country }}"{% endif %}>
                            </label>
                            {% if cust_id is None %}
                            <input type="submit" data-loading-text="submitting..." class="item-submit btn-design" value="submit">
                            {% endif %}
                        </fieldset>
                    </form>
                </div>                    
            </div>
            <div class="order-step-item order-step-item-last text-center">
                <div class="order-step-title"><div class="checkout-section-title">3.Payment</div><div>• Required</div></div>
                <div class="order-step-content">
                    <ul class="steps steps-vertical lg:steps-horizontal">
                        {% if step == 'buy' %}
                            <li class="step step-primary" id="submitted">Register</li>
                        {% else %}
                            <li class="step" id="submitted">Register</li>
                        {% endif %}
                        <li class="step">Place Order</li>
                        <li class="step">Ship</li>
                        <li class="step">Delivered</li>
                    </ul>
                </div>                    
            </div>
        </div>
        <div class="w-full md:w-1/4 sticky top-0 mt-4 md:mt-10 md:ml-4 p-4 border border-black rounded-none">
            <div class="border-b border-black pb-4 mb-4">
                <div class="text-lg">Order Summary</div>
            </div>
            
            {% if cart_items %}
                {% for item in cart_items %}
                    <div class="border-b border-black pb-4 mb-4">
                        <div class="text-lg">{{ item.product_name }}</div>
                    </div>
                {% endfor %}
                <div class="border-b border-black pb-4 mb-4">
                    <div class="text-lg">Total</div>
                    <p class="mt-2">Rs. {{ total_price }}</p>
                </div>
            {% else %}
                <div class="border-b border-black pb-4 mb-4">
                    <div class="text-lg">Poster</div>
                    <img src="https://via.placeholder.com/150" alt="Poster Image" class="w-full h-auto mt-2">
                </div>
                <div class="border-b border-black pb-4 mb-4">
                    <div class="text-lg">Total</div>
                    <p class="mt-2">Rs. XXXX</p>
                </div>
            {% endif %}
            
            <div class="text-center">
                <form method="POST" action="{% url 'inventory:order_info' %}">
                    {% csrf_token %}
                    <input type="hidden" name="cust_id" value="{{ cust_id }}">
                    <button type="submit" class="btn btn-primary rounded-none" {% if cust_id is None %}disabled{% endif %}>Place Order</button>
                </form>                    
            </div>
        </div>      
    </div>
</div>

{% endblock %}

inventory/templates/inventory/product.html
{% extends 'theme/base.html' %}
{% block content %}
<section class="section" id="tshirt">
    <h3 class="section-title">T-Shirt</h3>

    {% if page_obj %}
    {% for item in page_obj %}
    <div class="item-list">
        <div class="product-list-item">
            <div class="product-list-item-img-wrap overflow-x-scroll flex">
                {% for media in item.media_product_inventory.all %}
                <img src="{{ media.image }}" alt="{{ media.alt_text }}" class="product-list-images">
                {% endfor %}
            </div>
            <div id="add-to-cart-form" class="item-list-content-warp">
                <h2 class="item-list-title">{{ item.product.name }}</h2>
                <div class="product-list-price">Rs.{{ item.retail_price }}</div>
                <p class="paragraph">{{ item.product.description }}</p>
                <form class="item-add-to-cart" method="POST" action="{%url 'inventory:home'%}">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ item.product.pk }}">
                    <label>
                        <input type="number" name="quantity" class="item-count" min="1" value="1">
                    </label>
                    <input type="submit" data-loading-text="Adding to cart..." class="item-submit btn-design" value="Add to Cart">
                    <button type="submit" formaction="{% url 'inventory:buy_now' %}" class="item-submit btn-design button-filled">Buy Now</button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="flex justify-center mt-8 mb-8">
        <div class="join">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="join-item btn btn-outline">« Previous</a>
            {% else %}
            <button class="join-item btn btn-disabled ">« Previous</button>
            {% endif %}

            <span class="join-item btn">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="join-item btn btn-outline">Next »</a>
            {% else %}
            <button class="join-item btn btn-disabled">Next »</button>
            {% endif %}
        </div>
    </div>
    {% else %}
    <p>No products available.</p>
    {% endif %}
</section>
{% endblock %}


{% block Hero%}
<div class="swiper-container ml-14 mr-14">
  <div class="swiper-wrapper">
    <div class="swiper-slide flex items-center justify-center">
      <div class="flex-1 mr-8 ml-8">
        <h3 class="font-bold text-lg">Plain White T-shirt</h3>
        <p>This is a description of the first t-shirt in the swiper.</p>
      </div>
      <img src="#" alt="tshirt" class="shadow-lg rounded-md flex-1" />
    </div>
    <div class="swiper-slide flex items-center justify-center">
      <div class="flex-1 mr-8 ml-8">
        <h3 class="font-bold text-lg">Plain Black T-shirt</h3>
        <p>Best Quality tshirt.</p>
      </div>
      <img src="#" alt="tshirt" class="shadow-lg rounded-md flex-1" />
    </div>
    <div class="swiper-slide flex items-center justify-center">
      <div class="flex-1 mr-8 ml-8">
        <h3 class="font-bold text-lg">Tshirt 3</h3>
        <p>This is a description of the third t-shirt in the swiper.</p>
      </div>
      <img src="#" alt="tshirt" class="shadow-lg rounded-md flex-1" />
    </div>
  </div>
</div>
{% endblock %}